packet_dict = {
    "play": {
        "send": {
            0x04: "player position",
            0x05: "player look",
            0x06: "player position and look",
            0x07: "player digging",
        },
        "recv": {
            0x00: "keep alive",
            0x02: "chat message",
            0x03: "time update",
            0x06: "player health",
            0x08: "player position and look",
            0x0b: "animation",
            0x0c: "spawn player",

            0x12: "entity velocity",
            0x14: "entity init",
            0x15: "entity relative move",
            0x16: "entity look",
            0x17: "entity rel move and look",
            0x18: "entity teleport",
            0x19: "entity head look",
            0x1a: "entity status",

            0x1f: "player experience",

            0x21: "chunk data",
            0x22: "multi block change",
            0x23: "block change",
            0x26: "map chunk bulk",

            0x29: "sound effect",
            0x2c: "global entity (thunderbolt)",
            0x2f: "set slot",
            0x30: "window items",
            0x33: "update sign",
            0x35: "update block entity",

            0x37: "statistics",
            0x38: "player list entry",
            0x42: "combat",
            0x44: "world border",
        },
    },
}

enchant_dict = {
        0:  { "id": "protection", "name": "Protection", "max":"4", "use_on":"Armor" },
        1:  { "id": "fire_protection", "name": "Fire Protection", "max":"4", "use_on":"Armor" },
        2:  { "id": "feather_falling", "name": "Feather Falling", "max":"4", "use_on":"Boots" },
        3:  { "id": "blast_protection", "name": "Blast Protection", "max":"4", "use_on":"Armor" },
        4:  { "id": "projectile_protection", "name": "Projectile Protection", "max":"4", "use_on":"Armor" },
        5:  { "id": "respiration", "name": "Respiration", "max":"3", "use_on":"Helmets" },
        6:  { "id": "aqua_affinity", "name": "Aqua Affinity", "max":"1", "use_on":"Helmets" },
        7:  { "id": "thorns", "name": "Thorns", "max":"3", "use_on":"Armor" },
        8:  { "id": "depth_strider", "name": "Depth Strider", "max":"3", "use_on":"Boots" },

        16: { "id": "sharpness", "name": "Sharpness", "max":"5", "use_on":"Swords, Axes" },
        17: { "id": "smite", "name": "Smite", "max":"5", "use_on":"Swords, Axes" },
        18: { "id": "bane_of_arthropods", "name": "Bane of Arthropods", "max":"5", "use_on":"Swords, Axes" },
        19: { "id": "knockback", "name": "Knockback", "max":"2", "use_on":"Swords" },
        20: { "id": "fire_aspect", "name": "Fire Aspect", "max":"2", "use_on":"Swords" },
        21: { "id": "looting", "name": "Looting", "max":"3", "use_on":"Swords" },

        32: { "id": "efficiency", "name": "Efficiency", "max":"5", "use_on":"Pickaxes, Shovels, Axes, Shears" },
        33: { "id": "silk_touch", "name": "Silk Touch", "max":"1", "use_on":"Pickaxes, Shovels, Axes, Shears" },
        34: { "id": "unbreaking", "name": "Unbreaking", "max":"3", "use_on":"Any Item with Durability" },
        35: { "id": "fortune", "name": "Fortune", "max":"3", "use_on":"Pickaxes, Shovels, Axes" },

        48: { "id": "power", "name": "Power", "max":"5", "use_on":"Bow" },
        49: { "id": "punch", "name": "Punch", "max":"2", "use_on":"Bow" },
        50: { "id": "flame", "name": "Flame", "max":"1", "use_on":"Bow" },
        51: { "id": "infinity", "name": "Infinity", "max":"1", "use_on":"Bow" },

        61: { "id": "luck_of_the_sea", "name": "Luck of the Sea", "max":"3", "use_on":"Fishing Rod" },
        62: { "id": "lure", "name": "Lure", "max":"3", "use_on":"Fishing Rod" },
}

effect_dict = {
        1:  { "id": "speed", "name": "Speed" },
        2:  { "id": "slowness", "name": "Slowness" },
        3:  { "id": "haste", "name": "Haste" },
        4:  { "id": "mining_fatigue", "name": "Mining Fatigue" },
        5:  { "id": "strength", "name": "Strength" },
        6:  { "id": "instant_health", "name": "Instant Health" },
        7:  { "id": "instant_damage", "name": "Instant Damage" },
        8:  { "id": "jump_boost", "name": "Jump Boost" },
        9:  { "id": "nausea", "name": "Nausea" },
        10: { "id": "regeneration", "name": "Regeneration" },
        11: { "id": "resistance", "name": "Resistance" },
        12: { "id": "fire_resistance", "name": "Fire Resistance" },
        13: { "id": "water_breathing", "name": "Water Breathing" },
        14: { "id": "invisibility", "name": "Invisibility" },
        15: { "id": "blindness", "name": "Blindness" },
        16: { "id": "night_vision", "name": "Night vision" },
        17: { "id": "hunger", "name": "Hunger" },
        18: { "id": "weakness", "name": "Weakness" },
        19: { "id": "poison", "name": "Poison" },
        20: { "id": "wither", "name": "Wither" },
        21: { "id": "health_boost", "name": "Health Boost" },
        22: { "id": "absorption", "name": "Absorption" },
        23: { "id": "saturation", "name": "Saturation" },
}

# -1 is a custom entry for the player's inventory.
#   It has no ID, because it is never opened by the server.
# TODO add more inventory indices
window_dict = {
        -1: { "id": "inventory", "name": "Inventory",
            "out_index": 0, "crafting_index": 1, "armor_index": 5, "inventory_index": 9, "hotbar_index": 36 },
        0:  { "id": "chest", "name": "Chest/Large chest" },
        1:  { "id": "crafting_table", "name": "Workbench",
            "out_index": 0, "crafting_index": 1, "inventory_index": 10, "hotbar_index": 37 },
        2:  { "id": "furnace", "name": "Furnace",
            "smelted_index": 0, "fuel_index": 1, "out_index": 2, "inventory_index": 3, "hotbar_index": 30 },
        3:  { "id": "dispenser", "name": "Dispenser" },
        4:  { "id": "enchanting_table", "name": "Enchantment table" },
        5:  { "id": "brewing_stand", "name": "Brewing Stand" },
        6:  { "id": "villager", "name": "Npc trade" },
        7:  { "id": "beacon", "name": "Beacon" },
        8:  { "id": "anvil", "name": "Anvil" },
        9:  { "id": "hopper", "name": "Hopper" },
        10: { "id": "dropper", "name": "Dropper" },
        11: { "id": "EntityHorse", "name": "Horse" },
}

# Flags:
#   blocks only:
#     I: Has a different ID as an inventory item.
#     E: Requires a block entity to store additional data.
#     S: Requires additional data from the saved game's Data array to fully define the block.
#   blocks and items:
#     B: Requires additional data in the item's Damage field to fully define the inventory item.
#     D: Use the item's Damage field to define its durability.
# TODO convert flag field to boolean fields?

block_dict = {
        0x0:  { "id": "air", "name": "Air", "flags": "" },
        0x1:  { "id": "stone", "name": "Stone", "flags": "SB" },
        0x2:  { "id": "grass", "name": "Grass Block", "flags": "" },
        0x3:  { "id": "dirt", "name": "Dirt", "flags": "SB" },
        0x4:  { "id": "cobblestone", "name": "Cobblestone", "flags": "" },
        0x5:  { "id": "planks", "name": "Wood Planks", "flags": "SB" },
        0x6:  { "id": "sapling", "name": "Sapling", "flags": "SB" },
        0x7:  { "id": "bedrock", "name": "Bedrock", "flags": "" },
        0x8:  { "id": "flowing_water", "name": "Water", "flags": "S" },
        0x9:  { "id": "water", "name": "Stationary Water", "flags": "S" },
        0xA:  { "id": "flowing_lava", "name": "Lava", "flags": "S" },
        0xB:  { "id": "lava", "name": "Stationary Lava", "flags": "S" },
        0xC:  { "id": "sand", "name": "Sand", "flags": "SB" },
        0xD:  { "id": "gravel", "name": "Gravel", "flags": "" },
        0xE:  { "id": "gold_ore", "name": "Gold Ore", "flags": "" },
        0xF:  { "id": "iron_ore", "name": "Iron Ore", "flags": "" },
        0x10: { "id": "coal_ore", "name": "Coal Ore", "flags": "" },
        0x11: { "id": "log", "name": "Wood", "flags": "SB" },
        0x12: { "id": "leaves", "name": "Leaves", "flags": "SB" },
        0x13: { "id": "sponge", "name": "Sponge", "flags": "SB" },
        0x14: { "id": "glass", "name": "Glass", "flags": "" },
        0x15: { "id": "lapis_ore", "name": "Lapis Lazuli Ore", "flags": "" },
        0x16: { "id": "lapis_block", "name": "Lapis Lazuli Block", "flags": "" },
        0x17: { "id": "dispenser", "name": "Dispenser", "flags": "SE" },
        0x18: { "id": "sandstone", "name": "Sandstone", "flags": "SB" },
        0x19: { "id": "noteblock", "name": "Note Block", "flags": "E" },
        0x1A: { "id": "bed", "name": "Bed", "flags": "IS" },
        0x1B: { "id": "golden_rail", "name": "Powered Rail", "flags": "S" },
        0x1C: { "id": "detector_rail", "name": "Detector Rail", "flags": "S" },
        0x1D: { "id": "sticky_piston", "name": "Sticky Piston", "flags": "S" },
        0x1E: { "id": "web", "name": "Cobweb", "flags": "" },
        0x1F: { "id": "tallgrass", "name": "Grass", "flags": "SB" },
        0x20: { "id": "deadbush", "name": "Dead Bush", "flags": "" },
        0x21: { "id": "piston", "name": "Piston", "flags": "S" },
        0x22: { "id": "piston_head", "name": "Piston Extension", "flags": "S" },
        0x23: { "id": "wool", "name": "Wool", "flags": "SB" },
        0x24: { "id": "piston_extension", "name": "Block moved by Piston", "flags": "E" },
        0x25: { "id": "yellow_flower", "name": "Dandelion", "flags": "" },
        0x26: { "id": "red_flower", "name": "Poppy", "flags": "SB" },
        0x27: { "id": "brown_mushroom", "name": "Brown Mushroom", "flags": "" },
        0x28: { "id": "red_mushroom", "name": "Red Mushroom", "flags": "" },
        0x29: { "id": "gold_block", "name": "Block of Gold", "flags": "" },
        0x2A: { "id": "iron_block", "name": "Block of Iron", "flags": "" },
        0x2B: { "id": "double_stone_slab", "name": "Double Stone Slab", "flags": "ISB" },
        0x2C: { "id": "stone_slab", "name": "Stone Slab", "flags": "SB" },
        0x2D: { "id": "brick_block", "name": "Bricks", "flags": "" },
        0x2E: { "id": "tnt", "name": "TNT", "flags": "" },
        0x2F: { "id": "bookshelf", "name": "Bookshelf", "flags": "" },
        0x30: { "id": "mossy_cobblestone", "name": "Moss Stone", "flags": "" },
        0x31: { "id": "obsidian", "name": "Obsidian", "flags": "" },
        0x32: { "id": "torch", "name": "Torch", "flags": "S" },
        0x33: { "id": "fire", "name": "Fire", "flags": "S" },
        0x34: { "id": "mob_spawner", "name": "Monster Spawner", "flags": "E" },
        0x35: { "id": "oak_stairs", "name": "Oak Wood Stairs", "flags": "S" },
        0x36: { "id": "chest", "name": "Chest", "flags": "SE" },
        0x37: { "id": "redstone_wire", "name": "Redstone Wire", "flags": "IS" },
        0x38: { "id": "diamond_ore", "name": "Diamond Ore", "flags": "" },
        0x39: { "id": "diamond_block", "name": "Block of Diamond", "flags": "" },
        0x3A: { "id": "crafting_table", "name": "Crafting Table", "flags": "" },
        0x3B: { "id": "wheat", "name": "Wheat", "flags": "S" },
        0x3C: { "id": "farmland", "name": "Farmland", "flags": "S" },
        0x3D: { "id": "furnace", "name": "Furnace", "flags": "SE" },
        0x3E: { "id": "lit_furnace", "name": "Burning Furnace", "flags": "SE" },
        0x3F: { "id": "standing_sign", "name": "Standing Sign", "flags": "ISE" },
        0x40: { "id": "wooden_door", "name": "Oak Door", "flags": "IS" },
        0x41: { "id": "ladder", "name": "Ladder", "flags": "S" },
        0x42: { "id": "rail", "name": "Rail", "flags": "S" },
        0x43: { "id": "stone_stairs", "name": "Cobblestone Stairs", "flags": "S" },
        0x44: { "id": "wall_sign", "name": "Wall Sign", "flags": "ISE" },
        0x45: { "id": "lever", "name": "Lever", "flags": "S" },
        0x46: { "id": "stone_pressure_plate", "name": "Stone Pressure Plate", "flags": "S" },
        0x47: { "id": "iron_door", "name": "Iron Door", "flags": "IS" },
        0x48: { "id": "wooden_pressure_plate", "name": "Wooden Pressure Plate", "flags": "S" },
        0x49: { "id": "redstone_ore", "name": "Redstone Ore", "flags": "" },
        0x4A: { "id": "lit_redstone_ore", "name": "Glowing Redstone Ore", "flags": "" },
        0x4B: { "id": "unlit_redstone_torch", "name": "Redstone Torch (inactive)", "flags": "S" },
        0x4C: { "id": "redstone_torch", "name": "Redstone Torch (active)", "flags": "S" },
        0x4D: { "id": "stone_button", "name": "Stone Button", "flags": "S" },
        0x4E: { "id": "snow_layer", "name": "Snow", "flags": "SB" },
        0x4F: { "id": "ice", "name": "Ice", "flags": "" },
        0x50: { "id": "snow", "name": "Snow", "flags": "" },
        0x51: { "id": "cactus", "name": "Cactus", "flags": "S" },
        0x52: { "id": "clay", "name": "Clay", "flags": "" },
        0x53: { "id": "reeds", "name": "Sugar Cane", "flags": "IS" },
        0x54: { "id": "jukebox", "name": "Jukebox", "flags": "SE" },
        0x55: { "id": "fence", "name": "Fence", "flags": "" },
        0x56: { "id": "pumpkin", "name": "Pumpkin", "flags": "S" },
        0x57: { "id": "netherrack", "name": "Netherrack", "flags": "" },
        0x58: { "id": "soul_sand", "name": "Soul Sand", "flags": "" },
        0x59: { "id": "glowstone", "name": "Glowstone", "flags": "" },
        0x5A: { "id": "portal", "name": "Nether Portal", "flags": "" },
        0x5B: { "id": "lit_pumpkin", "name": "Jack o'Lantern", "flags": "S" },
        0x5C: { "id": "cake", "name": "Cake", "flags": "IS" },
        0x5D: { "id": "unpowered_repeater", "name": "Redstone Repeater (inactive)", "flags": "IS" },
        0x5E: { "id": "powered_repeater", "name": "Redstone Repeater (active)", "flags": "IS" },
        0x5F: { "id": "stained_glass", "name": "Stained Glass", "flags": "SB" },
        0x60: { "id": "trapdoor", "name": "Trapdoor", "flags": "S" },
        0x61: { "id": "monster_egg", "name": "Monster Egg", "flags": "SB" },
        0x62: { "id": "stonebrick", "name": "Stone Bricks", "flags": "SB" },
        0x63: { "id": "brown_mushroom_block", "name": "Brown Mushroom (block)", "flags": "S" },
        0x64: { "id": "red_mushroom_block", "name": "Red Mushroom (block)", "flags": "S" },
        0x65: { "id": "iron_bars", "name": "Iron Bars", "flags": "" },
        0x66: { "id": "glass_pane", "name": "Glass Pane", "flags": "" },
        0x67: { "id": "melon_block", "name": "Melon", "flags": "" },
        0x68: { "id": "pumpkin_stem", "name": "Pumpkin Stem", "flags": "S" },
        0x69: { "id": "melon_stem", "name": "Melon Stem", "flags": "S" },
        0x6A: { "id": "vine", "name": "Vines", "flags": "S" },
        0x6B: { "id": "fence_gate", "name": "Fence Gate", "flags": "S" },
        0x6C: { "id": "brick_stairs", "name": "Brick Stairs", "flags": "S" },
        0x6D: { "id": "stone_brick_stairs", "name": "Stone Brick Stairs", "flags": "S" },
        0x6E: { "id": "mycelium", "name": "Mycelium", "flags": "" },
        0x6F: { "id": "waterlily", "name": "Lily Pad", "flags": "" },
        0x70: { "id": "nether_brick", "name": "Nether Brick", "flags": "" },
        0x71: { "id": "nether_brick_fence", "name": "Nether Brick Fence", "flags": "" },
        0x72: { "id": "nether_brick_stairs", "name": "Nether Brick Stairs", "flags": "S" },
        0x73: { "id": "nether_wart", "name": "Nether Wart", "flags": "IS" },
        0x74: { "id": "enchanting_table", "name": "Enchantment Table", "flags": "E" },
        0x75: { "id": "brewing_stand", "name": "Brewing Stand", "flags": "ISE" },
        0x76: { "id": "cauldron", "name": "Cauldron", "flags": "IS" },
        0x77: { "id": "end_portal", "name": "End Portal", "flags": "E" },
        0x78: { "id": "end_portal_frame", "name": "End Portal Block", "flags": "S" },
        0x79: { "id": "end_stone", "name": "End Stone", "flags": "" },
        0x7A: { "id": "dragon_egg", "name": "Dragon Egg", "flags": "" },
        0x7B: { "id": "redstone_lamp", "name": "Redstone Lamp (inactive)", "flags": "" },
        0x7C: { "id": "lit_redstone_lamp", "name": "Redstone Lamp (active)", "flags": "" },
        0x7D: { "id": "double_wooden_slab", "name": "Double Wooden Slab", "flags": "SB" },
        0x7E: { "id": "wooden_slab", "name": "Wooden Slab", "flags": "SB" },
        0x7F: { "id": "cocoa", "name": "Cocoa", "flags": "IS" },
        0x80: { "id": "sandstone_stairs", "name": "Sandstone Stairs", "flags": "S" },
        0x81: { "id": "emerald_ore", "name": "Emerald Ore", "flags": "" },
        0x82: { "id": "ender_chest", "name": "Ender Chest", "flags": "SE" },
        0x83: { "id": "tripwire_hook", "name": "Tripwire Hook", "flags": "S" },
        0x84: { "id": "tripwire", "name": "Tripwire", "flags": "IS" },
        0x85: { "id": "emerald_block", "name": "Block of Emerald", "flags": "" },
        0x86: { "id": "spruce_stairs", "name": "Spruce Wood Stairs", "flags": "S" },
        0x87: { "id": "birch_stairs", "name": "Birch Wood Stairs", "flags": "S" },
        0x88: { "id": "jungle_stairs", "name": "Jungle Wood Stairs", "flags": "S" },
        0x89: { "id": "command_block", "name": "Command Block", "flags": "E" },
        0x8A: { "id": "beacon", "name": "Beacon", "flags": "E" },
        0x8B: { "id": "cobblestone_wall", "name": "Cobblestone Wall", "flags": "SB" },
        0x8C: { "id": "flower_pot", "name": "Flower Pot", "flags": "ISE" },
        0x8D: { "id": "carrots", "name": "Carrot", "flags": "IS" },
        0x8E: { "id": "potatoes", "name": "Potato", "flags": "IS" },
        0x8F: { "id": "wooden_button", "name": "Wooden Button", "flags": "S" },
        0x90: { "id": "skull", "name": "Mob head", "flags": "ISE" },
        0x91: { "id": "anvil", "name": "Anvil", "flags": "SB" },
        0x92: { "id": "trapped_chest", "name": "Trapped Chest", "flags": "SE" },
        0x93: { "id": "light_weighted_pressure_plate", "name": "Light Weighted Pressure Plate", "flags": "S" },
        0x94: { "id": "heavy_weighted_pressure_plate", "name": "Heavy Weighted Pressure Plate", "flags": "S" },
        0x95: { "id": "unpowered_comparator", "name": "Redstone Comparator", "flags": "IS" },
        0x96: { "id": "powered_comparator", "name": "Redstone Comparator", "flags": "IS" },
        0x97: { "id": "daylight_detector", "name": "Daylight Sensor", "flags": "E" },
        0x98: { "id": "redstone_block", "name": "Block of Redstone", "flags": "" },
        0x99: { "id": "quartz_ore", "name": "Nether Quartz Ore", "flags": "" },
        0x9A: { "id": "hopper", "name": "Hopper", "flags": "SE" },
        0x9B: { "id": "quartz_block", "name": "Block of Quartz", "flags": "SB" },
        0x9C: { "id": "quartz_stairs", "name": "Quartz Stairs", "flags": "S" },
        0x9D: { "id": "activator_rail", "name": "Activator Rail", "flags": "S" },
        0x9E: { "id": "dropper", "name": "Dropper", "flags": "SE" },
        0x9F: { "id": "stained_hardened_clay", "name": "Stained Clay", "flags": "SB" },
        0xA0: { "id": "stained_glass_pane", "name": "Stained Glass Pane", "flags": "SB" },
        0xA1: { "id": "leaves2", "name": "Leaves (Acacia/Dark Oak)", "flags": "SB" },
        0xA2: { "id": "log2", "name": "Wood (Acacia/Dark Oak)", "flags": "SB" },
        0xA3: { "id": "acacia_stairs", "name": "Acacia Wood Stairs", "flags": "S" },
        0xA4: { "id": "dark_oak_stairs", "name": "Dark Oak Wood Stairs", "flags": "S" },
        0xA5: { "id": "slime", "name": "Slime Block", "flags": "" },
        0xA6: { "id": "barrier", "name": "Barrier", "flags": "" },
        0xA7: { "id": "iron_trapdoor", "name": "Iron Trapdoor", "flags": "S" },
        0xA8: { "id": "prismarine", "name": "Prismarine", "flags": "SB" },
        0xA9: { "id": "sea_lantern", "name": "Sea Lantern", "flags": "" },
        0xAA: { "id": "hay_block", "name": "Hay Bale", "flags": "S" },
        0xAB: { "id": "carpet", "name": "Carpet", "flags": "SB" },
        0xAC: { "id": "hardened_clay", "name": "Hardened Clay", "flags": "" },
        0xAD: { "id": "coal_block", "name": "Block of Coal", "flags": "" },
        0xAE: { "id": "packed_ice", "name": "Packed Ice", "flags": "" },
        0xAF: { "id": "double_plant", "name": "Large Flowers", "flags": "SB" },
        0xB0: { "id": "standing_banner", "name": "Standing Banner", "flags": "ISE" },
        0xB1: { "id": "wall_banner", "name": "Wall Banner", "flags": "ISE" },
        0xB2: { "id": "daylight_detector_inverted", "name": "Inverted Daylight Sensor", "flags": "E" },
        0xB3: { "id": "red_sandstone", "name": "Red Sandstone", "flags": "SB" },
        0xB4: { "id": "red_sandstone_stairs", "name": "Red Sandstone Stairs", "flags": "S" },
        0xB5: { "id": "double_stone_slab2", "name": "Double Red Sandstone Slab", "flags": "S" },
        0xB6: { "id": "stone_slab2", "name": "Red Sandstone Slab", "flags": "S" },
        0xB7: { "id": "spruce_fence_gate", "name": "Spruce Fence Gate", "flags": "" },
        0xB8: { "id": "birch_fence_gate", "name": "Birch Fence Gate", "flags": "" },
        0xB9: { "id": "jungle_fence_gate", "name": "Jungle Fence Gate", "flags": "" },
        0xBA: { "id": "dark_oak_fence_gate", "name": "Dark Oak Fence Gate", "flags": "" },
        0xBB: { "id": "acacia_fence_gate", "name": "Acacia Fence Gate", "flags": "" },
        0xBC: { "id": "spruce_fence", "name": "Spruce Fence", "flags": "" },
        0xBD: { "id": "birch_fence", "name": "Birch Fence", "flags": "" },
        0xBE: { "id": "jungle_fence", "name": "Jungle Fence", "flags": "" },
        0xBF: { "id": "dark_oak_fence", "name": "Dark Oak Fence", "flags": "" },
        0xC0: { "id": "acacia_fence", "name": "Acacia Fence", "flags": "" },
        0xC1: { "id": "spruce_door", "name": "Spruce Door", "flags": "IS" },
        0xC2: { "id": "birch_door", "name": "Birch Door", "flags": "IS" },
        0xC3: { "id": "jungle_door", "name": "Jungle Door", "flags": "IS" },
        0xC4: { "id": "acacia_door", "name": "Acacia Door", "flags": "IS" },
        0xC5: { "id": "dark_oak_door", "name": "Dark Oak Door", "flags": "IS" },
}

item_dict = {
        0x100: { "id": "iron_shovel", "name": "Iron Shovel", "flags": "D" },
        0x101: { "id": "iron_pickaxe", "name": "Iron Pickaxe", "flags": "D" },
        0x102: { "id": "iron_axe", "name": "Iron Axe", "flags": "D" },
        0x103: { "id": "flint_and_steel", "name": "Flint and Steel", "flags": "D" },
        0x104: { "id": "apple", "name": "Apple", "flags": "" },
        0x105: { "id": "bow", "name": "Bow", "flags": "D" },
        0x106: { "id": "arrow", "name": "Arrow", "flags": "" },
        0x107: { "id": "coal", "name": "Coal", "flags": "B" },
        0x108: { "id": "diamond", "name": "Diamond", "flags": "" },
        0x109: { "id": "iron_ingot", "name": "Iron Ingot", "flags": "" },
        0x10A: { "id": "gold_ingot", "name": "Gold Ingot", "flags": "" },
        0x10B: { "id": "iron_sword", "name": "Iron Sword", "flags": "D" },
        0x10C: { "id": "wooden_sword", "name": "Wooden Sword", "flags": "D" },
        0x10D: { "id": "wooden_shovel", "name": "Wooden Shovel", "flags": "D" },
        0x10E: { "id": "wooden_pickaxe", "name": "Wooden Pickaxe", "flags": "D" },
        0x10F: { "id": "wooden_axe", "name": "Wooden Axe", "flags": "D" },
        0x110: { "id": "stone_sword", "name": "Stone Sword", "flags": "D" },
        0x111: { "id": "stone_shovel", "name": "Stone Shovel", "flags": "D" },
        0x112: { "id": "stone_pickaxe", "name": "Stone Pickaxe", "flags": "D" },
        0x113: { "id": "stone_axe", "name": "Stone Axe", "flags": "D" },
        0x114: { "id": "diamond_sword", "name": "Diamond Sword", "flags": "D" },
        0x115: { "id": "diamond_shovel", "name": "Diamond Shovel", "flags": "D" },
        0x116: { "id": "diamond_pickaxe", "name": "Diamond Pickaxe", "flags": "D" },
        0x117: { "id": "diamond_axe", "name": "Diamond Axe", "flags": "D" },
        0x118: { "id": "stick", "name": "Stick", "flags": "" },
        0x119: { "id": "bowl", "name": "Bowl", "flags": "" },
        0x11A: { "id": "mushroom_stew", "name": "Mushroom Stew", "flags": "" },
        0x11B: { "id": "golden_sword", "name": "Golden Sword", "flags": "D" },
        0x11C: { "id": "golden_shovel", "name": "Golden Shovel", "flags": "D" },
        0x11D: { "id": "golden_pickaxe", "name": "Golden Pickaxe", "flags": "D" },
        0x11E: { "id": "golden_axe", "name": "Golden Axe", "flags": "D" },
        0x11F: { "id": "string", "name": "String", "flags": "" },
        0x120: { "id": "feather", "name": "Feather", "flags": "" },
        0x121: { "id": "gunpowder", "name": "Gunpowder", "flags": "" },
        0x122: { "id": "wooden_hoe", "name": "Wooden Hoe", "flags": "D" },
        0x123: { "id": "stone_hoe", "name": "Stone Hoe", "flags": "D" },
        0x124: { "id": "iron_hoe", "name": "Iron Hoe", "flags": "D" },
        0x125: { "id": "diamond_hoe", "name": "Diamond Hoe", "flags": "D" },
        0x126: { "id": "golden_hoe", "name": "Golden Hoe", "flags": "D" },
        0x127: { "id": "wheat_seeds", "name": "Seeds", "flags": "" },
        0x128: { "id": "wheat", "name": "Wheat", "flags": "" },
        0x129: { "id": "bread", "name": "Bread", "flags": "" },
        0x12A: { "id": "leather_helmet", "name": "Leather Cap", "flags": "D" },
        0x12B: { "id": "leather_chestplate", "name": "Leather Tunic", "flags": "D" },
        0x12C: { "id": "leather_leggings", "name": "Leather Pants", "flags": "D" },
        0x12D: { "id": "leather_boots", "name": "Leather Boots", "flags": "D" },
        0x12E: { "id": "chainmail_helmet", "name": "Chain Helmet", "flags": "D" },
        0x12F: { "id": "chainmail_chestplate", "name": "Chain Tunic", "flags": "D" },
        0x130: { "id": "chainmail_leggings", "name": "Chain Leggings", "flags": "D" },
        0x131: { "id": "chainmail_boots", "name": "Chain Boots", "flags": "D" },
        0x132: { "id": "iron_helmet", "name": "Iron Helmet", "flags": "D" },
        0x133: { "id": "iron_chestplate", "name": "Iron Chestplate", "flags": "D" },
        0x134: { "id": "iron_leggings", "name": "Iron Leggings", "flags": "D" },
        0x135: { "id": "iron_boots", "name": "Iron Boots", "flags": "D" },
        0x136: { "id": "diamond_helmet", "name": "Diamond Helmet", "flags": "D" },
        0x137: { "id": "diamond_chestplate", "name": "Diamond Chestplate", "flags": "D" },
        0x138: { "id": "diamond_leggings", "name": "Diamond Leggings", "flags": "D" },
        0x139: { "id": "diamond_boots", "name": "Diamond Boots", "flags": "D" },
        0x13A: { "id": "golden_helmet", "name": "Golden Helmet", "flags": "D" },
        0x13B: { "id": "golden_chestplate", "name": "Golden Chestplate", "flags": "D" },
        0x13C: { "id": "golden_leggings", "name": "Golden Leggings", "flags": "D" },
        0x13D: { "id": "golden_boots", "name": "Golden Boots", "flags": "D" },
        0x13E: { "id": "flint", "name": "Flint", "flags": "" },
        0x13F: { "id": "porkchop", "name": "Raw Porkchop", "flags": "" },
        0x140: { "id": "cooked_porkchop", "name": "Cooked Porkchop", "flags": "" },
        0x141: { "id": "painting", "name": "Painting", "flags": "" },
        0x142: { "id": "golden_apple", "name": "Golden Apple", "flags": "B" },
        0x143: { "id": "sign", "name": "Sign", "flags": "" },
        0x144: { "id": "wooden_door", "name": "Oak Door", "flags": "" },
        0x145: { "id": "bucket", "name": "Bucket", "flags": "" },
        0x146: { "id": "water_bucket", "name": "Water Bucket", "flags": "" },
        0x147: { "id": "lava_bucket", "name": "Lava Bucket", "flags": "" },
        0x148: { "id": "minecart", "name": "Minecart", "flags": "" },
        0x149: { "id": "saddle", "name": "Saddle", "flags": "" },
        0x14A: { "id": "iron_door", "name": "Iron Door", "flags": "" },
        0x14B: { "id": "redstone", "name": "Redstone", "flags": "" },
        0x14C: { "id": "snowball", "name": "Snowball", "flags": "" },
        0x14D: { "id": "boat", "name": "Boat", "flags": "" },
        0x14E: { "id": "leather", "name": "Leather", "flags": "" },
        0x14F: { "id": "milk_bucket", "name": "Milk", "flags": "" },
        0x150: { "id": "brick", "name": "Brick", "flags": "" },
        0x151: { "id": "clay_ball", "name": "Clay", "flags": "" },
        0x152: { "id": "reeds", "name": "Sugar Cane", "flags": "" },
        0x153: { "id": "paper", "name": "Paper", "flags": "" },
        0x154: { "id": "book", "name": "Book", "flags": "" },
        0x155: { "id": "slime_ball", "name": "Slimeball", "flags": "" },
        0x156: { "id": "chest_minecart", "name": "Minecart with Chest", "flags": "" },
        0x157: { "id": "furnace_minecart", "name": "Minecart with Furnace", "flags": "" },
        0x158: { "id": "egg", "name": "Egg", "flags": "" },
        0x159: { "id": "compass", "name": "Compass", "flags": "" },
        0x15A: { "id": "fishing_rod", "name": "Fishing Rod", "flags": "D" },
        0x15B: { "id": "clock", "name": "Clock", "flags": "" },
        0x15C: { "id": "glowstone_dust", "name": "Glowstone Dust", "flags": "" },
        0x15D: { "id": "fish", "name": "Raw Fish", "flags": "B" },
        0x15E: { "id": "cooked_fish", "name": "Cooked Fish", "flags": "B" },
        0x15F: { "id": "dye", "name": "Dye", "flags": "B" },
        0x160: { "id": "bone", "name": "Bone", "flags": "" },
        0x161: { "id": "sugar", "name": "Sugar", "flags": "" },
        0x162: { "id": "cake", "name": "Cake", "flags": "" },
        0x163: { "id": "bed", "name": "Bed", "flags": "" },
        0x164: { "id": "repeater", "name": "Redstone Repeater", "flags": "" },
        0x165: { "id": "cookie", "name": "Cookie", "flags": "" },
        0x166: { "id": "filled_map", "name": "Map", "flags": "B" },
        0x167: { "id": "shears", "name": "Shears", "flags": "D" },
        0x168: { "id": "melon", "name": "Melon", "flags": "" },
        0x169: { "id": "pumpkin_seeds", "name": "Pumpkin Seeds", "flags": "" },
        0x16A: { "id": "melon_seeds", "name": "Melon Seeds", "flags": "" },
        0x16B: { "id": "beef", "name": "Raw Beef", "flags": "" },
        0x16C: { "id": "cooked_beef", "name": "Steak", "flags": "" },
        0x16D: { "id": "chicken", "name": "Raw Chicken", "flags": "" },
        0x16E: { "id": "cooked_chicken", "name": "Cooked Chicken", "flags": "" },
        0x16F: { "id": "rotten_flesh", "name": "Rotten Flesh", "flags": "" },
        0x170: { "id": "ender_pearl", "name": "Ender Pearl", "flags": "" },
        0x171: { "id": "blaze_rod", "name": "Blaze Rod", "flags": "" },
        0x172: { "id": "ghast_tear", "name": "Ghast Tear", "flags": "" },
        0x173: { "id": "gold_nugget", "name": "Gold Nugget", "flags": "" },
        0x174: { "id": "nether_wart", "name": "Nether Wart", "flags": "" },
        0x175: { "id": "potion", "name": "Potion", "flags": "B" },
        0x176: { "id": "glass_bottle", "name": "Glass Bottle", "flags": "" },
        0x177: { "id": "spider_eye", "name": "Spider Eye", "flags": "" },
        0x178: { "id": "fermented_spider_eye", "name": "Fermented Spider Eye", "flags": "" },
        0x179: { "id": "blaze_powder", "name": "Blaze Powder", "flags": "" },
        0x17A: { "id": "magma_cream", "name": "Magma Cream", "flags": "" },
        0x17B: { "id": "brewing_stand", "name": "Brewing Stand", "flags": "" },
        0x17C: { "id": "cauldron", "name": "Cauldron", "flags": "" },
        0x17D: { "id": "ender_eye", "name": "Eye of Ender", "flags": "" },
        0x17E: { "id": "speckled_melon", "name": "Glistering Melon", "flags": "" },
        0x17F: { "id": "spawn_egg", "name": "Spawn Egg", "flags": "B" },
        0x180: { "id": "experience_bottle", "name": "Bottle o' Enchanting", "flags": "" },
        0x181: { "id": "fire_charge", "name": "Fire Charge", "flags": "" },
        0x182: { "id": "writable_book", "name": "Book and Quill", "flags": "" },
        0x183: { "id": "written_book", "name": "Written Book", "flags": "" },
        0x184: { "id": "emerald", "name": "Emerald", "flags": "" },
        0x185: { "id": "item_frame", "name": "Item Frame", "flags": "" },
        0x186: { "id": "flower_pot", "name": "Flower Pot", "flags": "" },
        0x187: { "id": "carrot", "name": "Carrot", "flags": "" },
        0x188: { "id": "potato", "name": "Potato", "flags": "" },
        0x189: { "id": "baked_potato", "name": "Baked Potato", "flags": "" },
        0x18A: { "id": "poisonous_potato", "name": "Poisonous Potato", "flags": "" },
        0x18B: { "id": "map", "name": "Empty Map", "flags": "" },
        0x18C: { "id": "golden_carrot", "name": "Golden Carrot", "flags": "" },
        0x18D: { "id": "skull", "name": "Mob head", "flags": "B" },
        0x18E: { "id": "carrot_on_a_stick", "name": "Carrot on a Stick", "flags": "D" },
        0x18F: { "id": "nether_star", "name": "Nether Star", "flags": "" },
        0x190: { "id": "pumpkin_pie", "name": "Pumpkin Pie", "flags": "" },
        0x191: { "id": "fireworks", "name": "Firework Rocket", "flags": "" },
        0x192: { "id": "firework_charge", "name": "Firework Star", "flags": "" },
        0x193: { "id": "enchanted_book", "name": "Enchanted Book", "flags": "" },
        0x194: { "id": "comparator", "name": "Redstone Comparator", "flags": "" },
        0x195: { "id": "netherbrick", "name": "Nether Brick", "flags": "" },
        0x196: { "id": "quartz", "name": "Nether Quartz", "flags": "" },
        0x197: { "id": "tnt_minecart", "name": "Minecart with TNT", "flags": "" },
        0x198: { "id": "hopper_minecart", "name": "Minecart with Hopper", "flags": "" },
        0x199: { "id": "prismarine_shard", "name": "Prismarine Shard", "flags": "" },
        0x19A: { "id": "prismarine_crystals", "name": "Prismarine Crystals", "flags": "" },
        0x19B: { "id": "rabbit", "name": "Raw Rabbit", "flags": "" },
        0x19C: { "id": "cooked_rabbit", "name": "Cooked Rabbit", "flags": "" },
        0x19D: { "id": "rabbit_stew", "name": "Rabbit Stew", "flags": "" },
        0x19E: { "id": "rabbit_foot", "name": "Rabbit's Foot", "flags": "" },
        0x19F: { "id": "rabbit_hide", "name": "Rabbit Hide", "flags": "" },
        0x1A0: { "id": "armor_stand", "name": "Armor Stand", "flags": "" },
        0x1A1: { "id": "iron_horse_armor", "name": "Iron Horse Armor", "flags": "" },
        0x1A2: { "id": "golden_horse_armor", "name": "Golden Horse Armor", "flags": "" },
        0x1A3: { "id": "diamond_horse_armor", "name": "Diamond Horse Armor", "flags": "" },
        0x1A4: { "id": "lead", "name": "Lead", "flags": "" },
        0x1A5: { "id": "name_tag", "name": "Name Tag", "flags": "" },
        0x1A6: { "id": "command_block_minecart", "name": "Minecart with Command Block", "flags": "" },
        0x1A7: { "id": "mutton", "name": "Raw Mutton", "flags": "" },
        0x1A8: { "id": "cooked_mutton", "name": "Cooked Mutton", "flags": "" },
        0x1A9: { "id": "banner", "name": "Banner", "flags": "" },
        0x1AB: { "id": "spruce_door", "name": "Spruce Door", "flags": "" },
        0x1AC: { "id": "birch_door", "name": "Birch Door", "flags": "" },
        0x1AD: { "id": "jungle_door", "name": "Jungle Door", "flags": "" },
        0x1AE: { "id": "acacia_door", "name": "Acacia Door", "flags": "" },
        0x1AF: { "id": "dark_oak_door", "name": "Dark Oak Door", "flags": "" },
        0x8D0: { "id": "record_13", "name": "13 Disc", "flags": "" },
        0x8D1: { "id": "record_cat", "name": "Cat Disc", "flags": "" },
        0x8D2: { "id": "record_blocks", "name": "Blocks Disc", "flags": "" },
        0x8D3: { "id": "record_chirp", "name": "Chirp Disc", "flags": "" },
        0x8D4: { "id": "record_far", "name": "Far Disc", "flags": "" },
        0x8D5: { "id": "record_mall", "name": "Mall Disc", "flags": "" },
        0x8D6: { "id": "record_mellohi", "name": "Mellohi Disc", "flags": "" },
        0x8D7: { "id": "record_stal", "name": "Stal Disc", "flags": "" },
        0x8D8: { "id": "record_strad", "name": "Strad Disc", "flags": "" },
        0x8D9: { "id": "record_ward", "name": "Ward Disc", "flags": "" },
        0x8DA: { "id": "record_11", "name": "11 Disc", "flags": "" },
        0x8DB: { "id": "record_wait", "name": "Wait Disc", "flags": "" },
}

entity_dict = {
        0x01: { "id": "Item", "name": "Dropped item", "type": "drop" },
        0x02: { "id": "XPOrb", "name": "Experience Orb", "type": "drop" },

        0x08: { "id": "LeashKnot", "name": "Lead knot", "type": "immobile" },
        0x09: { "id": "Painting", "name": "Painting", "type": "immobile" },
        0x12: { "id": "ItemFrame", "name": "Item Frame", "type": "immobile" },
        0x1E: { "id": "ArmorStand", "name": "Armor Stand", "type": "immobile" },
        0xC8: { "id": "EnderCrystal", "name": "Ender Crystal", "type": "immobile" },

        0x0A: { "id": "Arrow", "name": "Shot arrow", "type": "projectile" },
        0x0B: { "id": "Snowball", "name": "Thrown snowball", "type": "projectile" },
        0x0C: { "id": "Fireball", "name": "Ghast fireball", "type": "projectile" },
        0x0D: { "id": "SmallFireball", "name": "Blaze fireball", "type": "projectile" },
        0x0E: { "id": "ThrownEnderpearl", "name": "Thrown Ender Pearl", "type": "projectile" },
        0x0F: { "id": "EyeOfEnderSignal", "name": "Thrown Eye of Ender", "type": "projectile" },
        0x10: { "id": "ThrownPotion", "name": "Thrown splash potion", "type": "projectile" },
        0x11: { "id": "ThrownExpBottle", "name": "Thrown Bottle o' Enchanting", "type": "projectile" },
        0x13: { "id": "WitherSkull", "name": "Wither Skull", "type": "projectile" },
        0x16: { "id": "FireworksRocketEntity", "name": "Firework Rocket", "type": "projectile" },

        0x14: { "id": "PrimedTnt", "name": "Primed TNT", "type": "block" },
        0x15: { "id": "FallingSand", "name": "Falling block", "type": "block" },

        0x28: { "id": "MinecartCommandBlock", "name": "Minecart with Command Block", "type": "vehicle" },
        0x29: { "id": "Boat", "name": "Boat", "type": "vehicle" },
        0x2A: { "id": "MinecartRideable", "name": "Minecart", "type": "vehicle" },
        0x2B: { "id": "MinecartChest", "name": "Minecart with Chest", "type": "vehicle" },
        0x2C: { "id": "MinecartFurnace", "name": "Minecart with Furnace", "type": "vehicle" },
        0x2D: { "id": "MinecartTNT", "name": "Minecart with TNT", "type": "vehicle" },
        0x2E: { "id": "MinecartHopper", "name": "Minecart with Hopper", "type": "vehicle" },
        0x2F: { "id": "MinecartSpawner", "name": "Minecart with Spawner", "type": "vehicle" },

        0x30: { "id": "Mob", "name": "Mob", "type": "generic" },
        0x31: { "id": "Monster", "name": "Monster", "type": "generic" },

        0x32: { "id": "Creeper", "name": "Creeper", "type": "hostile" },
        0x33: { "id": "Skeleton", "name": "Skeleton Wither Skeleton", "type": "hostile" },
        0x34: { "id": "Spider", "name": "Spider", "type": "hostile" },
        0x35: { "id": "Giant", "name": "Giant", "type": "hostile" },
        0x36: { "id": "Zombie", "name": "Zombie Zombie Villager", "type": "hostile" },
        0x37: { "id": "Slime", "name": "Slime", "type": "hostile" },
        0x38: { "id": "Ghast", "name": "Ghast", "type": "hostile" },
        0x39: { "id": "PigZombie", "name": "Zombie Pigman", "type": "hostile" },
        0x3A: { "id": "Enderman", "name": "Enderman", "type": "hostile" },
        0x3B: { "id": "CaveSpider", "name": "Cave Spider", "type": "hostile" },
        0x3C: { "id": "Silverfish", "name": "Silverfish", "type": "hostile" },
        0x3D: { "id": "Blaze", "name": "Blaze", "type": "hostile" },
        0x3E: { "id": "LavaSlime", "name": "Magma Cube", "type": "hostile" },
        0x3F: { "id": "EnderDragon", "name": "Ender Dragon", "type": "hostile" },
        0x40: { "id": "WitherBoss", "name": "Wither", "type": "hostile" },
        0x42: { "id": "Witch", "name": "Witch", "type": "hostile" },
        0x43: { "id": "Endermite", "name": "Endermite", "type": "hostile" },
        0x44: { "id": "Guardian", "name": "Guardian Elder Guardian", "type": "hostile" },
        0x65: { "id": "Rabbit", "name": "Killer Rabbit", "type": "hostile" },

        0x41: { "id": "Bat", "name": "Bat", "type": "passive" },
        0x5A: { "id": "Pig", "name": "Pig", "type": "passive" },
        0x5B: { "id": "Sheep", "name": "Sheep", "type": "passive" },
        0x5C: { "id": "Cow", "name": "Cow", "type": "passive" },
        0x5D: { "id": "Chicken", "name": "Chicken", "type": "passive" },
        0x5E: { "id": "Squid", "name": "Squid", "type": "passive" },
        0x5F: { "id": "Wolf", "name": "Wolf", "type": "passive" },
        0x60: { "id": "MushroomCow", "name": "Mooshroom", "type": "passive" },
        0x61: { "id": "SnowMan", "name": "Snow Golem", "type": "passive" },
        0x62: { "id": "Ozelot", "name": "Ocelot", "type": "passive" },
        0x63: { "id": "VillagerGolem", "name": "Iron Golem", "type": "passive" },
        0x64: { "id": "EntityHorse", "name": "Horse", "type": "passive" },
        0x65: { "id": "Rabbit", "name": "Rabbit", "type": "passive" },

        0x78: { "id": "Villager", "name": "Villager", "type": "npc" },
}

